// Next
import type { Metadata } from "next";
// Styles
import "./globals.css";
// Prismic
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "../prismicio";
// Google Analytics
import { GoogleAnalytics } from "@next/third-parties/google"
// Fonts
import { Raleway, Lora } from "next/font/google";
// Components
import Navigation from "@/src/_components/navigation";
import Footer from "@/src/_components/footer";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-raleway",
})

const lora = Lora({
  weight: ["700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-lora",
})

const gaId = process.env.NEXT_PUBLIC_GA_ID;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable} ${lora.variable}`}>
      <head>
        <script
          type="module"
          dangerouslySetInnerHTML={{
            __html: `import BugsnagPerformance from '//d2wy8f7a9ursnm.cloudfront.net/v1/bugsnag-performance.min.js'; BugsnagPerformance.start({ apiKey: '125d4e1a653190795d94c6d854a434d4' });`,
          }}
        />
      </head>
      <body className="antialiased">
        <Providers>
          <div className="flex min-h-screen flex-col" id="layout-container">
            <Navigation />
            <main className="flex-1">
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
      {gaId && <GoogleAnalytics gaId={gaId} />}
      <PrismicPreview repositoryName={repositoryName} />
    </html>
  );
}
