// Next
import type { Metadata } from "next";
// Styles
import "./globals.css";
// Prismic
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "../prismicio";
// Google Analytics
import { GoogleAnalytics } from "@next/third-parties/google" 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gaId = process.env.NEXT_PUBLIC_GA_ID;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
      {gaId && <GoogleAnalytics gaId={gaId} />}
      <PrismicPreview repositoryName={repositoryName} />
    </html>
  );
}
