// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  image_and_text: dynamic(() => import("./ImageAndText")),
  password_form: dynamic(() => import("./PasswordForm")),
  team: dynamic(() => import("./Team")),
};
