// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  password_form: dynamic(() => import("./PasswordForm")),
  team: dynamic(() => import("./Team")),
};
