// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_us: dynamic(() => import("./ContactUs")),
  hero: dynamic(() => import("./Hero")),
  image_and_text: dynamic(() => import("./ImageAndText")),
  // investment_chart: dynamic(() => import("./InvestmentChart")), Not used
  password_form: dynamic(() => import("./PasswordForm")),
  team: dynamic(() => import("./Team")),
};
